### ISSUE TITLE
qrl-cli lattice not implemented

### ISSUE THREAD

**Issue by Bodisatva** [theQRL/qrl-cli#48]
```qrl-cli --version
@theqrl/cli/1.8.0 linux-x64 node-v15.6.0
```
 ```qrl-cli lattice``` command doesn't exist and doesn't match the github https://github.com/theQRL/qrl-cli#qrl-cli-create-lattice description. it is still ```qrl-cli create-lattice```

**Comment by jplomas** [comment]
Tidied up in 1.10.2 release - thanks
